spring:
  application:
    name: ${APP_NAME}
  profiles:
    active: ${PROFILE:test}


logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - [service=${spring.application.name}] [profile=${spring.profiles.active:default}] %msg%n"
  level:
    root: INFO
